import PDFDocument from 'pdfkit';
import { Client, IssueTag } from '../types/client';

interface ReferralPdfInput {
  client: Client;
  officeName: string;
  issues: IssueTag[];
}

export function buildReferralPdf({ client, officeName, issues }: ReferralPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).font('Helvetica-Bold').text('DOLE Public Assistance and Complaints Unit');
    doc.fontSize(14).font('Helvetica').text('Referral Form', { align: 'left' });
    doc.moveDown();
    doc.fontSize(9).fillColor('#666').text(`Reference No.: ${client.reference_no}`);
    doc.text(`Date: ${client.transaction_date}`);
    doc.fillColor('#000');
    doc.moveDown();

    function field(label: string, value: string) {
      doc.font('Helvetica-Bold').fontSize(10).text(label, { continued: true });
      doc.font('Helvetica').text(` ${value}`);
    }

    field('Client Name:', `${client.first_name} ${client.last_name}`);
    field('Referred To:', officeName);
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(10).text('Reason for Referral:');
    doc.font('Helvetica').fontSize(10).text(client.referred_reason ?? '—');
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').fontSize(10).text('Tagged Issues:');
    doc.font('Helvetica').fontSize(10);
    if (issues.length === 0) {
      doc.text('—');
    } else {
      for (const issue of issues) {
        const label = issue.issue_description
          ? `${issue.category_group} — ${issue.category_name}: ${issue.issue_description}`
          : `${issue.category_group} — ${issue.category_name}`;
        doc.text(`• ${label}`);
      }
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#666').text(
      'This form is system-generated by the PACU Information System and reflects the record on file at the time of printing.'
    );

    doc.end();
  });
}
